;;
;;
;; Testing `convex.shell.catch`.
;;
;;


;;;;;;;;;;


(def T
     $.test)


;;;;;;;;;; Test suites


(defn suite.push-pop

  ^{:doc {:description "Testing low-level pushing and popping."}}

  []

  (T/group '((T/path.conj 'low-level)

             (def handler-1
                  '(def foo
                        :handler-1))

             (T/trx '(query (and (= handler-1
                                    ($.catch/push handler-1))
                                 (= handler-1
                                    (first $.catch/*stack*))))
                    {:description "Push."})

             (T/trx '(let [stack $.catch/*stack*
                           res   (do
                                   ($.catch/push handler-1)
                                   ($.catch/drop))]
                       (and (= handler-1
                               res)
                            (= stack
                               $.catch/*stack*)))
                    {:description "Drop."})

              (T/trx '(query (let [stack $.catch/*stack*
                                   trx+  $.trx/*list*]
                               ($.catch/push handler-1)
                               ($.catch/pop)
                               (= (cons handler-1
                                        trx+)
                                  $.trx/*list*)))
                     {:description "Pop."})


              (T/group '((T/path.conj 'catching)

                         ($.catch/push handler-1)

                         ($.catch/push '(assert false))

                         (assert false)

                         (T/trx '(= :handler-1
                                    foo)
                                {:description "Error bubbled to non-failing handler."}))))))



(defn suite.rethrow

  ^{:doc {:description "Rethrowing exceptions."}}
  
  []

  (T/group '((T/path.conj 'rethrow)

             (T/group '((T/path.conj 'success)
                        (def ex
                             {:code       :TEST
                              :exception? true
                              :foo        :bar})
                        (T/fail (fn [x]
                                  (= x
                                     ex))
                                `($.catch/!.rethrow (quote ~ex))
                                {:description "Properly rethrown."})))

             (T/group '((T/path.conj 'failure)
                        (T/fail.code #{:ASSERT}
                                     '($.catch/!.rethrow 42)
                                     {:description "Only exceptions can be rethrown."}))))))



(defn suite.safe

  ^{:doc {:description "Testing `safe`."}}

  []

  (T/group '((T/path.conj 'safe)

             (T/group '((T/path.conj "Success without catch nor finally.")
                        ($.catch/!.safe '(inc 42))
                        (T/trx '(= $/*result*
                                   43)
                               {:description "Trial executed normally."})))

             (T/group '((T/path.conj "Fail without catch nor finally.")
                        (T/fail.code #{:FROM-TRY}
                                     '($.catch/!.safe '(fail :FROM-TRY
                                                             nil))
                                     {:description "Exception is thrown normally."})))

             (T/group '((T/path.conj "Success with catch.")
                        ($.catch/!.safe '(inc 42)
                                        '(def x-catch
                                              :catch))
                        (T/trx '(= $/*result*
                                   43)
                               {:description "Result comes from trial"})
                        (T/trx '(not (defined? x-catch))
                               {:description "Catch is not executed."})))

             (T/group '((T/path.conj "Fail with catch.")
                        ($.catch/!.safe '(fail :FROM-TRY
                                               nil)
                                        '{:catch $/*result*})
                        (T/trx '(= (:code (:catch $/*result*))
                                   :FROM-TRY)
                               {:description "Exception as result in catch."})))

             (T/group '((T/path.conj "Fail with catch which fails as well.")
                        (T/fail (fn [ex]
                                  (and (= (ex :code)
                                          :FROM-CATCH)
                                       (= ((ex :message) :code)
                                          :FROM-TRY)))
                                '($.catch/!.safe '(fail :FROM-TRY
                                                        nil)
                                                 '(fail :FROM-CATCH
                                                        $/*result*))
                                {:description "Exception from catch bubbles up."})))

             (T/group '((T/path.conj "Success with finally.")
                        ($.catch/!.safe '(inc 42)
                                        nil
                                        '(do
                                           (def x-finally
                                                {:finally $/*result*})
                                           :finally))
                        (T/trx '(= $/*result*
                                   43)
                               {:description "Result comes from trial."})
                        (T/trx '(= (:finally x-finally)
                                   43)
                               {:description "Finally was executed."})))

             (T/group '((T/path.conj "Fail with finally.")
                        (T/fail.code #{:FROM-TRY}
                                     '($.catch/!.safe '(fail :FROM-TRY
                                                             nil)
                                                      nil
                                                      '(do
                                                         (def x-finally
                                                              {:finally $/*result*})
                                                         :finally))
                                     {:description "Exception rethrown."})
                        (T/trx '(= (:code (:finally x-finally))
                                   :FROM-TRY)
                               {:description "Finally was executed."})))

             (T/group '((T/path.conj "Fail with catch which fails as well.")
                        (T/fail.code #{:FROM-FINALLY}
                                     '($.catch/!.safe '(fail :FROM-TRY
                                                             nil)
                                                      nil
                                                      '(fail :FROM-FINALLY
                                                             nil))
                                     {:description "Exception from finally bubbles up."})))

             (T/group '((T/path.conj "Success with catch and finally.")
                        ($.catch/!.safe '(inc 42)
                                        '(def x-catch
                                              {:catch $/*result*})
                                        '(do
                                           (def x-finally
                                               {:finally $/*result*})
                                           :finally))
                        (T/trx '(= $/*result*
                                   43)
                               {:description "Result comes from trial."})
                        (T/trx '(not (defined? x-catch))
                               {:description "Catch is never executed."})
                        (T/trx '(= (:finally x-finally)
                                   43)
                               {:description "Finally was executed."})))

             (T/group '((T/path.conj "Fail with catch and finally.")
                        ($.catch/!.safe '(fail :FROM-TRY
                                               nil)
                                        '(do
                                           (def x-catch
                                                {:catch $/*result*})
                                           :catch)
                                        '(do
                                           (def x-finally
                                                {:finally $/*result*})
                                           :finally))
                        (T/trx '(= $/*result*
                                   :catch)
                               {:description "Result comes from catch."})
                        (T/trx '(= (:code (:catch x-catch))
                                   :FROM-TRY)
                               {:description "Exception as result in catch."})
                        (T/trx '(= (:finally x-finally)
                                   :catch)
                               {:description "Finally executed with result from catch."})))

             (T/group '((T/path.conj "Success with catch but failing finally.")
                        (T/fail (fn [ex]
                                  (and (= (ex :code)
                                          :FROM-FINALLY)
                                       (= (ex :message)
                                          43)))
                                '($.catch/!.safe '(inc 42)
                                                 :CATCH
                                                 '(fail :FROM-FINALLY
                                                        $/*result*))
                                {:description "Finally exception bubbles up."})))

             (T/group '((T/path.conj "Fail with catch but failing finally.")
                         (T/fail (fn [ex]
                                   (and (= (ex :code)
                                           :FROM-FINALLY)
                                        (= (ex :message)
                                           :CATCH)))
                                 '($.catch/!.safe '(fail FROM-TRY
                                                         nil)
                                                  :CATCH
                                                  '(fail :FROM-FINALLY
                                                         $/*result*))
                                 {:description "Finally exception bubbles up."})))

             (T/group '((T/path.conj "Fail with failing catch but healthy finally.")
                        (defn test-ex
                          [ex]
                          (and (= (ex :code)
                                  :FROM-CATCH)
                               (= ((ex :message) :code)
                                  :FROM-TRY)))
                        (T/fail test-ex
                                '($.catch/!.safe '(fail :FROM-TRY
                                                        nil)
                                                 '(fail :FROM-CATCH
                                                        $/*result*)
                                                 '(do
                                                    (def x-finally
                                                         {:finally $/*result*})
                                                    :finally))
                                {:description "Exception from catch bubbles up."})
                        (T/trx '(test-ex (x-finally :finally))
                               {:description "Finally was executed."})))

             (T/group '((T/path.conj "Fail with failing catch and failing finally.")
                        (T/fail (fn [ex-finally]
                                  (and (= (ex-finally :code)
                                          :FROM-FINALLY)
                                       (let [ex-catch (ex-finally :message)]
                                         (and (= (ex-catch :code)
                                                 :FROM-CATCH)
                                              (= ((ex-catch :message) :code)
                                                 :FROM-TRY)))))
                                '($.catch/!.safe '(fail :FROM-TRY
                                                        nil)
                                                 '(fail :FROM-CATCH
                                                        $/*result*)
                                                 '(fail :FROM-FINALLY
                                                        $/*result*))
                                {:description "Exception from finally bubbles up."}))))))


;;;


(defn suite.main

  ^{:doc {:description "Main test suite."}}

  []

  (T/group '((T/path.conj 'convex.shell.account)
             (suite.rethrow)
             (suite.push-pop)
             (suite.safe))))


;;;


(suite.main)
(T/print "convex.shell.catch")
